name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc
        pip install .[full]  # Install your package with full dependencies

    - name: Generate Documentation
      run: pdoc -o docs fastdeck

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push'  # Only deploy on pushes to main, not on PRs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true  # This will keep your gh-pages branch clean

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/
